// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SynchronizationTool.Demo.Database.Context;

#nullable disable

namespace SynchronizationTool.Demo.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20260429093824_syncTool")]
    partial class syncTool
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SynchronizationTool.Database.Models.Change", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChangeLogId")
                        .HasColumnType("uuid");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangeLogId");

                    b.ToTable("Change", "sync");
                });

            modelBuilder.Entity("SynchronizationTool.Database.Models.ChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClientVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("ChangeLog", "sync");
                });

            modelBuilder.Entity("SynchronizationTool.Database.Models.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("entity", "sync");
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_type_id");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_id");

                    b.Property<string>("MqttCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mqtt_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("device_id");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("HomeId");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.DeviceState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid>("StateTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_type_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("device_state_id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("StateTypeId");

                    b.ToTable("device_state", (string)null);
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.DeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("device_type_id");

                    b.ToTable("device_type", (string)null);
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("home_id");

                    b.ToTable("home", (string)null);
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.StateType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeCommand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("change_command");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_type_id");

                    b.HasKey("Id")
                        .HasName("state_type_id");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("state_type", (string)null);
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("user_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("UserHome", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_id");

                    b.HasKey("UserId", "HomeId")
                        .HasName("user_home_pk");

                    b.HasIndex("HomeId");

                    b.ToTable("user_home", (string)null);
                });

            modelBuilder.Entity("SynchronizationTool.Database.Models.Change", b =>
                {
                    b.HasOne("SynchronizationTool.Database.Models.ChangeLog", "ChangeLog")
                        .WithMany("Changes")
                        .HasForeignKey("ChangeLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeLog");
                });

            modelBuilder.Entity("SynchronizationTool.Database.Models.ChangeLog", b =>
                {
                    b.HasOne("SynchronizationTool.Database.Models.Entity", "Entity")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.Device", b =>
                {
                    b.HasOne("SynchronizationTool.Demo.Database.Models.publicSchema.DeviceType", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("device_device_type_id_fkey");

                    b.HasOne("SynchronizationTool.Demo.Database.Models.publicSchema.Home", "Home")
                        .WithMany("Devices")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("device_home_id_fkey");

                    b.Navigation("DeviceType");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.DeviceState", b =>
                {
                    b.HasOne("SynchronizationTool.Demo.Database.Models.publicSchema.Device", "Device")
                        .WithMany("DeviceStates")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("device_state_device_id_fkey");

                    b.HasOne("SynchronizationTool.Demo.Database.Models.publicSchema.StateType", "StateType")
                        .WithMany("DeviceStates")
                        .HasForeignKey("StateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("device_state_state_type_id_fkey");

                    b.Navigation("Device");

                    b.Navigation("StateType");
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.StateType", b =>
                {
                    b.HasOne("SynchronizationTool.Demo.Database.Models.publicSchema.DeviceType", "DeviceType")
                        .WithMany("StateTypes")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("state_type_device_type_id_fkey");

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("UserHome", b =>
                {
                    b.HasOne("SynchronizationTool.Demo.Database.Models.publicSchema.Home", null)
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_home_home_id_fkey");

                    b.HasOne("SynchronizationTool.Demo.Database.Models.publicSchema.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_home_user_id_fkey");
                });

            modelBuilder.Entity("SynchronizationTool.Database.Models.ChangeLog", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("SynchronizationTool.Database.Models.Entity", b =>
                {
                    b.Navigation("ChangeLogs");
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.Device", b =>
                {
                    b.Navigation("DeviceStates");
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.DeviceType", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("StateTypes");
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.Home", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SynchronizationTool.Demo.Database.Models.publicSchema.StateType", b =>
                {
                    b.Navigation("DeviceStates");
                });
#pragma warning restore 612, 618
        }
    }
}
