// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SynchronizationTool.Demo.Database.Models;
using SynchronizationTool.Demo.Database.Models.publicSchema;

namespace SynchronizationTool.Demo.Database.Context;

public partial class DemoContext
{

    public virtual DbSet<Device> Devices { get; set; }

    public virtual DbSet<DeviceState> DeviceStates { get; set; }

    public virtual DbSet<DeviceType> DeviceTypes { get; set; }

    public virtual DbSet<Home> Homes { get; set; }

    public virtual DbSet<StateType> StateTypes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Device>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("device_id");

            entity.ToTable("device");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.DeviceTypeId).HasColumnName("device_type_id");
            entity.Property(e => e.HomeId).HasColumnName("home_id");
            entity.Property(e => e.MqttCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("mqtt_code");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");

            entity.HasOne(d => d.DeviceType).WithMany(p => p.Devices)
                .HasForeignKey(d => d.DeviceTypeId)
                .HasConstraintName("device_device_type_id_fkey");

            entity.HasOne(d => d.Home).WithMany(p => p.Devices)
                .HasForeignKey(d => d.HomeId)
                .HasConstraintName("device_home_id_fkey");
        });

        modelBuilder.Entity<DeviceState>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("device_state_id");

            entity.ToTable("device_state");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.DeviceId).HasColumnName("device_id");
            entity.Property(e => e.StateTypeId).HasColumnName("state_type_id");
            entity.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("value");

            entity.HasOne(d => d.Device).WithMany(p => p.DeviceStates)
                .HasForeignKey(d => d.DeviceId)
                .HasConstraintName("device_state_device_id_fkey");

            entity.HasOne(d => d.StateType).WithMany(p => p.DeviceStates)
                .HasForeignKey(d => d.StateTypeId)
                .HasConstraintName("device_state_state_type_id_fkey");
        });

        modelBuilder.Entity<DeviceType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("device_type_id");

            entity.ToTable("device_type");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Home>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("home_id");

            entity.ToTable("home");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
        });

        modelBuilder.Entity<StateType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("state_type_id");

            entity.ToTable("state_type");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.ChangeCommand)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("change_command");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("code");
            entity.Property(e => e.DeviceTypeId).HasColumnName("device_type_id");

            entity.HasOne(d => d.DeviceType).WithMany(p => p.StateTypes)
                .HasForeignKey(d => d.DeviceTypeId)
                .HasConstraintName("state_type_device_type_id_fkey");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("user_id");

            entity.ToTable("user");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("email");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("password");

            entity.HasMany(d => d.Homes).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "UserHome",
                    r => r.HasOne<Home>().WithMany()
                        .HasForeignKey("HomeId")
                        .HasConstraintName("user_home_home_id_fkey"),
                    l => l.HasOne<User>().WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_home_user_id_fkey"),
                    j =>
                    {
                        j.HasKey("UserId", "HomeId").HasName("user_home_pk");
                        j.ToTable("user_home");
                        j.IndexerProperty<Guid>("UserId").HasColumnName("user_id");
                        j.IndexerProperty<Guid>("HomeId").HasColumnName("home_id");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}