// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SynchronizationTool.Demo.Database.Models.publicSchema;
using SynchronizationTool.Database;

namespace SynchronizationTool.Demo.Database.Models.publicSchema
{
    [SynchronisatedAttribute(Id = "66e1a232-fae6-4f06-89f4-8afec8e107d6")]

    public partial class Device
    {
    }
}

