// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SynchronizationTool.Demo.Database.Models.publicSchema;


namespace SynchronizationTool.Demo.Database.Models.publicSchema;

public partial class Device
{
    public Guid Id { get; set; }

    public string MqttCode { get; set; }

    public string Name { get; set; }

    public Guid DeviceTypeId { get; set; }

    public Guid HomeId { get; set; }

    public virtual ICollection<DeviceState> DeviceStates { get; set; } = new List<DeviceState>();

    public virtual DeviceType DeviceType { get; set; }

    public virtual Home Home { get; set; }
}