// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SynchronizationTool.Demo.Database.Models.publicSchema;


namespace SynchronizationTool.Demo.Database.Models.publicSchema;

public partial class DeviceState
{
    public Guid Id { get; set; }

    public Guid DeviceId { get; set; }

    public Guid StateTypeId { get; set; }

    public string Value { get; set; }

    public virtual Device Device { get; set; }

    public virtual StateType StateType { get; set; }
}