// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SynchronizationTool.Demo.Database.Models.publicSchema;


namespace SynchronizationTool.Demo.Database.Models.publicSchema;

public partial class Home
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Device> Devices { get; set; } = new List<Device>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}