// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SynchronizationTool.Demo.Database.Models.publicSchema;


namespace SynchronizationTool.Demo.Database.Models.publicSchema;

public partial class User
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }

    public virtual ICollection<Home> Homes { get; set; } = new List<Home>();
}